### PR TITLE
Create support files and dashboard to answer BQ 5.2

### PR DESCRIPTION
**Pull request by jsurrea**
Added the files that support the Dashboard developed in Looker

### CODE REVIEW

**Review by SnowArtz — CHANGES_REQUESTED** [review]
Please use the folder structure, we proposed.

**Comment by jsurrea** [comment]
Hey @SnowArtz you reviewed a draft, my apologies. Now it is ready :)

**Comment by SnowArtz** [comment]
> Hey @SnowArtz you reviewed a draft, my apologies. Now it is ready :)

Dont worry bro, it happens sometimes

**Review by iGotty — APPROVED** [review]

**Review by SnowArtz — APPROVED** [review]
It looks perfect

**Comment by iGotty** [comment]
> > Hey @SnowArtz you reviewed a draft, my apologies. Now it is ready :)
> 
> Dont worry bro, it happens sometimes

True

**Pull request merged**
