### PR TITLE
Add Mockups, Dashboard and generators of BQ 4.1

### LINKED ISSUE #5: Create support files and dashboard to answer BQ 4.1
Acceptance criteria:

* Add Excel file with Mockup Data
* Add Screenshot/PDF of Dashboard developed with Looker
* Add any other relevant documentation

### PR DESCRIPTION
**Pull request by SnowArtz**
Excel Mockup, Dashboard and generator of BQ4.1 added.

### CODE REVIEW

**Review by jsurrea — APPROVED** [review]
Great Job!

**Review by jsurrea — CHANGES_REQUESTED** [review]
Please merge into develop!

**Review by jdcastellanosb73 — COMMENTED** [review]
i think you want to merge 1 commit into main and not into develop  branch

**Comment by SnowArtz** [comment]
> Please merge into develop!

You are right, sorry and ty

**Comment by SnowArtz** [comment]
> i think you want to merge 1 commit into main and not into develop branch

You are right, sorry and ty

**Review by jsurrea — APPROVED** [review]

**Review by iGotty — APPROVED** [review]
👍

**Pull request merged**
